# Generated by Django 4.2.3 on 2023-07-22 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_article_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='kunde',
            new_name='customer',
        ),
    ]
